name: 'Build with CMake'

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: System Packages
        shell: pwsh
        run: |
          choco install ninja

      # Conan is used due to its simplicity as a package manager
      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Install dependencies
        shell: pwsh
        run: |
          # First set up the conanfile
          $dependencies = @("boost/1.82.0")
          $generators   = @("cmake", "cmake_find_package")
          "[requires]" | Out-File conanfile.txt
          $dependencies | ForEach-Object { $_ | Add-Content conanfile.txt }
          "`n[generators]" | Add-Content conanfile.txt
          $generators | ForEach-Object { $_ | Add-Content conanfile.txt }
          # Set up conan
          conan profile detect
          # Install dependencies
          conan install . --build=missing

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update -yq
      #     sudo apt-get install -y --no-install-recommends $BUILD_DEPS

      # - name: Generate makefile using CMake
      #   run: |
      #     mkdir cmake_build
      #     cd cmake_build
      #     cmake .. -DBUILD_LIBRARIES=OFF

      # - name: Run make
      #   run: |
      #     cd cmake_build
      #     cmake --build .

      # - name: Run test
      #   run: |
      #     cd cmake_build
      #     ctest -j$(nproc)
